### ISSUE TITLE
error in obj coordinates

### ISSUE THREAD

**Issue by jbjuin** [cprogrammer1994/ModernGL.ext.obj#2]
Hi, 

I export 3 .obj from blender corresponding to 3 parallel planes of different sizes and with a small z shift.

Export/import works well (with the corrections you mentionned).
I export with the same "Up/Forward" values for the 3 planes.
Do you make an assumption about the order of the coordinates in the obj ?

I load the 3 planes with ModernGL and render it to an image file. 
The image render fine but **the planes are not located at the right position.**
They are almost at the good position but with a relative shift of 20%...

To check where the error comes from I loaded in a new blender scene the 3 planes and they show up at the correct location.

Do you know where it could come from ?

**Comment by cprogrammer1994** [comment]
- Is your code opensource? I could take a look.
- Can you paste the file and the snippet for loading OBJ files?
- How do you create the projection / lookat matrices?

Please use the `Obj` class from version `0.3.0` I kept the functions from `0.1.0` (backward compatibility) but they will be deprecated in future releases.

**Comment by jbjuin** [comment]
I will try to reproduce it with the minimal code and post it here. I will do that tomorrow.

**Comment by cprogrammer1994** [comment]
I made a small example rendering Suzanne from blender. I used blender to export the OBJ.

### [Rendering Blender's Suzanne with ModernGL](https://github.com/cprogrammer1994/Blender-Suzanne)

Export settings:

![obj settings](https://user-images.githubusercontent.com/11232402/27445030-a96924f6-5778-11e7-9c5b-4ec9afc17f1d.png)

**Comment by jbjuin** [comment]
Hi, ok i was confused. It's not a problem of objects positions but of inversed texture coordinates. Here are 2 images showing the problem & the code.

The blende origin scene:

![screenshot_original_scene](https://user-images.githubusercontent.com/2361571/27474136-aa3963d0-5801-11e7-8920-0bcb638c28aa.png)

The ModernGL rendered scene:

![render](https://user-images.githubusercontent.com/2361571/27474146-b87a6390-5801-11e7-833e-1eafdeb1ec6b.jpg)

Objects positions look ok but the textures are upside down.
Here is the code:

```python
import numpy as np
import ModernGL

from datetime import datetime
from ModernGL.ext import obj
from PIL import Image
from pyrr import Matrix44


# Context creation
ctx = ModernGL.create_standalone_context()

# Shaders
vertex_shader_source   = open('./shader.vert').read()
fragment_shader_source = open('./shader.frag').read()
fragment_shader = ctx.fragment_shader(fragment_shader_source)
vertex_shader   = ctx.vertex_shader(vertex_shader_source)
PROG = ctx.program([vertex_shader, fragment_shader])


projection = Matrix44.orthogonal_projection(-2, 2, -2, 2, 0.1, 1000)

eye_position_start = [0.0, 0.0, 1.0]
look_at_target     = [0.0, 0.0, 0.0]

lookat = Matrix44.look_at(
    eye_position_start,
    look_at_target,
    (-1.0, 0.0, 0.0),
)
mvp = projection * lookat

PROG.uniforms['Light'].value = (1.0, 1.0, 1.0)
PROG.uniforms['Color'].value = (1.0, 1.0, 1.0, 0.0)
PROG.uniforms['Mvp'].write(mvp.astype('float32').tobytes())



class Plane:
    def __init__(self, obj_filename, diffuse_texture_filename, index=0):
        print("obj: ", obj_filename)
        print("tex: ", diffuse_texture_filename)

        self.obj_filename                   = obj_filename
        self.vertex_data                    = obj.objects.Obj.open(self.obj_filename).pack()

        self.diffuse_texture_filename       = diffuse_texture_filename
        self.diffuse_texture_image          = Image.open(self.diffuse_texture_filename)

        self.texture                        = ctx.texture(self.diffuse_texture_image.size, 3, self.diffuse_texture_image.tobytes())
        self.texture.build_mipmaps()

        # vertex
        self.vbo                            = ctx.buffer(self.vertex_data)
        self.vao                            = ctx.simple_vertex_array(PROG, self.vbo, ["in_vert", "in_text", "in_norm"])


plane0 = Plane("./plane_0.obj", "./0.jpg", index=0)
plane1 = Plane("./plane_1.obj", "./1.jpg", index=1)
plane2 = Plane("./plane_2.obj", "./2.jpg", index=2)


fbo = ctx.framebuffer(ctx.renderbuffer((512, 512)))
fbo.use()
ctx.enable(ModernGL.DEPTH_TEST)
ctx.clear(0.9, 0.9, 0.9)

plane0.texture.use()
plane0.vao.render()

plane2.texture.use()
plane2.vao.render()

plane1.texture.use()
plane1.vao.render()

# Loading the image using Pillow
data = fbo.read(components=3, alignment=1)
img = Image.frombytes('RGB', fbo.size, data).transpose(Image.FLIP_TOP_BOTTOM)
img.save("./render.jpg")
```

Shaders are the one you provide in your Headless example.
Any idea ?

**Comment by cprogrammer1994** [comment]
please paste the `plane_0.obj` and the `shader.vert`

**Comment by cprogrammer1994** [comment]
Replace `Image.open(self.diffuse_texture_filename)` with `Image.open(self.diffuse_texture_filename).transpose(Image.FLIP_TOP_BOTTOM)`

**Comment by cprogrammer1994** [comment]
You have to flip the texture because Pillow's [coordinate system](http://pillow.readthedocs.io/en/3.4.x/handbook/concepts.html#coordinate-system) is different from the one used in [OpenGL](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexImage2D.xhtml)

> **glTexImage2D:** The first element corresponds to the lower left corner of the texture image. Subsequent elements progress left-to-right through the remaining texels in the lowest row of the texture image, and then in successively higher rows of the texture image. The final element corresponds to the upper right corner of the texture image.

**Comment by jbjuin** [comment]
Yep !
